import google.generativeai as genai
from config import GEMINI_API_KEY
from services.qdrant_service import query_documents

if GEMINI_API_KEY:
    genai.configure(api_key=GEMINI_API_KEY)
    llm_model = genai.GenerativeModel("gemini-2.0-flash")
else:
    llm_model = None
    print("⚠️ GEMINI_API_KEY not found!")

def ask_llm(question: str, top_k: int = 3):
    """
    Generate an answer using Gemini LLM with retrieved context.
    Falls back to general knowledge if no relevant documents are found.
    """
    docs_with_scores = query_documents(question, top_k)
    
    if not llm_model:
        return {"answer": "Gemini API not configured.", "source": "error"}

    # Check if we have relevant documents (score threshold)
    relevant_docs = [doc for doc, score in docs_with_scores if score > 0.3]
    
    if relevant_docs:
        # We have relevant context from database
        context = "\n\n".join(
            [f"Document {i+1}:\n{doc}" for i, doc in enumerate(relevant_docs)]
        )
        
        prompt = f"""You are a skilled DevOps assistant with expertise in cloud, CI/CD, containers, and automation.  
Use the provided context from our internal knowledge base as your foundation.  
Craft a lively, natural, and insightful answer that feels conversational and human —  
as if generated by an expert with GenAI-level communication skills.  

Focus on clarity, flow, and helpfulness while keeping technical accuracy.  
If the context lacks full information, reason smartly and fill gaps naturally without fabricating facts. 

        Context from Knowledge Base:
        {context}

        Question: {question}

        IMPORTANT FORMATTING INSTRUCTIONS:
        - Use markdown formatting for clarity and structure
        - For code examples, ALWAYS use proper code blocks with language tags:
        - Use bold for important terms, concepts, or key points
        - Use inline code for commands, file names, variables, or technical terms
        - Use ## for main section headers (sparingly)
        - Use ### for subsection headers if needed
        - Use bullet points with • for lists
        - Use numbered lists (1. 2. 3.) for sequential steps or procedures
        - Keep explanations clear and concise
        - Add blank lines between sections for readability

        Answer:
    """
        try:
            response = llm_model.generate_content(prompt)
            return {"answer": response.text, "source": "database"}
        except Exception as e:
            return {"answer": f"Error generating response: {e}", "source": "error"}
    else:
        
        # No relevant documents found, use LLM's general knowledge
        prompt = f"""You are a helpful DevOps assistant. The user asked a question but we don't have specific information about it in our internal knowledge base.

        Question: {question}

        IMPORTANT FORMATTING INSTRUCTIONS:
        - Use markdown formatting for clarity and structure
        - For code examples, ALWAYS use proper code blocks with language tags:
        - Use bold for important terms, concepts, or key points
        - Use inline code for commands, file names, variables, or technical terms
        - Use ## for main section headers (sparingly)
        - Use ### for subsection headers if needed
        - Use bullet points with • for lists
        - Use numbered lists (1. 2. 3.) for sequential steps or procedures
        - Keep explanations clear and concise
        - Be helpful and accurate
        - If you're not sure, say so

        Answer:
        """
        try:
            response = llm_model.generate_content(prompt)
            return {"answer": response.text, "source": "llm_knowledge"}
        except Exception as e:
            return {"answer": f"Error generating response: {e}", "source": "error"}